catppuccin/jetbrains

- src/main/resources/themes/Catppuccin.xml
Resolves #6
TODO and FIXME use the same style as far as I can tell (the screenshot doesn't show it, but I also tried FIXME)
> Update TODO/FIXME color

- src/main/resources/themes/Catppuccin.theme.json
- src/main/resources/themes/Catppuccin.xml
This makes some minor changes to the language defaults for the Instance Field to change the color (actually to match what's in VSCode)
It also adds the ENUM_IDENTIFIER to change the Enum color from the same Orange color to the Light Blue color, which also matches what's in VSCode.
Rider doesn't actually have specific XAML support, so its still not *perfect* but this at least adds some color differentiation.
This fixes issue #8 
Here's a quick example:
> Updates for better XAML support

- src/main/resources/themes/Catppuccin.xml
The invalid character in the current theme has a very similar color to the background, thus unless the error background is active, the character is almost invisible. The error background would be fine, if it would reliably show up no matter what...
I've gone ahead and changed it so instead of using the red error, it follows the VSCode theme to make the invalid character very obvious no matter what (the below character is a different version of the semicolon, not the normal one):
This fixes #12
> Changes invalid character to match VSCode

- src/main/resources/themes/Catppuccin.theme.json
Currently, on the [New JetBrains UI](https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/) (and even a little bit on the old one), the rows in the file explorer are very tight, which is hard to read.
This PR proposes to raise the height to 24. In my opinion, it also looks pretty good on the old UI.
| Before this PR | After this PR |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/12123721/182162652-4c41170f-8d2b-4967-860f-cb29ed75cbdb.png) | ![after](https://user-images.githubusercontent.com/12123721/182162719-36436995-88b2-4025-a839-afca1566a582.png) |
| Default New UI | Old UI after this PR |
| --- | --- |
| ![Capture d’écran, le 2022-08-01 à 15 44 19](https://user-images.githubusercontent.com/12123721/182162856-03a0074b-c8 …
> Fix tree row height

- CHANGELOG.md
- generateFlavours/template.xml
Makes the terminal follow the color specs in [our style guide](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#terminals).
Screenshot (custom Mocha with `#000000` background):
> fix: terminal colors

- CHANGELOG.md
- generateFlavours/template.xml
Using `surface2`, the same color as the keyword under caret border.
Before:
After:
> fix: matched brace border

- generateFlavours/main.ts
Makes the file tree mantle, the top nav bar mantle, and styles the CheckBoxes/Buttons/Spinners/RadioButtons, to better blend in with the new Panel colors in the settings.
Will close #27, but some more work is needed to further improve appearance.
> feat: styling for new UI

- CHANGELOG.md
- generateFlavours/main.ts
- generateFlavours/template.xml
Uses a `text`/ rainbow color mix of 60%/40%, e.g. `#cdd6f4`/`#f38ba8` => `#dcb8d6`
> fix: semantic highlights

- CHANGELOG.md
- generateFlavours/main.ts
Add missing style to memory indicator
> feat: add styles to memory indicator

- CHANGELOG.md
- generateFlavours/main.ts
Add missing style to main toolbar elements
> feat: add styles to main toolbar

- .github/workflows/build.yml
- .github/workflows/publish.yml
- build.gradle.kts
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
This PR moves away from IntelliJ 2021, as this is really hard to work on the UI with IntelliJ 2021 that does not have the new UI. And while a lot of users have move to the new UI, this PR seems important to improve the quality of next releases.
The new platformVersion with this PR is ~~2023.2~~ 2022.2.
> build: update `platformVersion` to 2022.2

- CHANGELOG.md
- generateFlavours/template.xml
> fix: nix syntax highlighting

- CHANGELOG.md
- generateFlavours/template.xml
Before it pretty much inherited from the default template language foreground, which made everything a single color instead of following the highlighting set up.
| Before | After |
|--------|--------|
| ![before](https://github.com/catppuccin/jetbrains/assets/43011723/b44cfcd4-e8f4-4402-82f2-35363d648274) | ![after](https://github.com/catppuccin/jetbrains/assets/43011723/08d2e9bf-6a3a-4199-8d0a-5a5f54e0e52d) |
> fix: Prevent the Go Template background colors to inherit default

- CHANGELOG.md
- generateFlavours/main.ts
Set **secondaryBackground** as background color for plugin tags.
> feat: add background color for plugin tags

- CHANGELOG.md
- generateFlavours/template.xml
| Before | After |
|--------|--------|
| ![before](https://github.com/catppuccin/jetbrains/assets/43011723/bd3c7a7c-7544-47e6-89ac-04bea8bbbb41) | ![after](https://github.com/catppuccin/jetbrains/assets/43011723/3c7a256f-fef7-4a3d-ab71-d2edf8799644) |
- Closes #75
> feat: make references in go comments distinguishable

- CHANGELOG.md
- generateFlavours/template.xml
Previously when searching by using the "Replace in files" feature the background was of color `base`, which isn't ideal. Changed to be the same as other backgrounds when searching, which results in:
| Before | After |
|--------|--------|
| ![Before 'Replace in files'](https://github.com/catppuccin/jetbrains/assets/43011723/4e860e14-19a2-4fcf-9b33-5a227af5861c) | ![After 'Replace in files'](https://github.com/catppuccin/jetbrains/assets/43011723/95e1474c-bf82-43d3-b82a-40bb53df8600)| 
At the same time it apparently helps to solve one part of #72, specifically the first issue the user mentioned - not sure what they mean with the second though:
| Before | After |
|--------|--------|
| ![Select statement before](https://github.com/catppuccin/jetbrains/assets/43011723/62766f8a-9b1c-4ba5-977b-8d …
> feat: add background to search results

- CHANGELOG.md
- generateFlavours/main.ts
- generateFlavours/template.xml
It may seem subtle at first glance but I think it's much more balanced like that. This also fixes list item height that were really small in some menus.
> refactor: refine the UI colors

- CHANGELOG.md
- generateFlavours/ui.theme.json
> fix: improve contrast of `SearchMatch` on Latte

- generateFlavours/editor.xml
> fix: change unused code colour to `overlay2`

- generateFlavours/editor.xml
> fix: set error stripe mark for selected identifiers to teal

- CHANGELOG.md
- generateFlavours/editor.xml
This is same color as keywords, which is what intellij default color scheme uses.
Before:
After:
Alternative options:
`DEFAULT_PREDEFINED_SYMBOL` uses `lavender` with italics. I think it could make sense to use `lavender`, but predefined types appearing italic would look weird, IMHO.
Another option is to use `yellow` and make it same color as other types (`String` in screenshot).
> fix: set scala predefined types to `yellow`

- CHANGELOG.md
- generateFlavours/ui.theme.json
Themes text like this in the UI.
> fix: set `Component.infoForeground` to `subtext0`

- CHANGELOG.md
- generateFlavours/ui.theme.json
The selected one is gray out and the other have the panel color.
> fix(UI): theme macOS project tabs

- CHANGELOG.md
- generateFlavours/editor.xml
Initial changes didn't fit quite right. Instead, colors are set to more closely resemble xml colors. The style guide is rather hard to represent currently given the options for xaml styling are extremely limited. Any other opportunities for changes will have to wait.
> feat(xaml): improve syntax highlighting

- CHANGELOG.md
- generateFlavours/main.ts
- generateFlavours/ui.theme.json
> fix: highlight current branch in git log pane

- CHANGELOG.md
- generateFlavours/ui.theme.json
Solves #190.
Inspired by this [comment](https://youtrack.jetbrains.com/issue/JBR-7981).
Tested on 2 unrelated install.
[Catppuccin Theme-3.4.0-crash-fix.zip](https://github.com/user-attachments/files/18621488/Catppuccin.Theme-3.4.0-crash-fix.zip)
> fix: IDE freezing/crashing by setting `paintBorder: false`
